/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleBar: typeof import('./src/components/ArticleBar/ArticleBar.vue')['default']
    BlogEvent: typeof import('./src/components/BlogEvent/BlogEvent.vue')['default']
    Card: typeof import('./src/components/Card/Card.vue')['default']
    Comment: typeof import('./src/components/Comment/Comment.vue')['default']
    CommentBar: typeof import('./src/components/Comment/CommentBar.vue')['default']
    CommentSection: typeof import('./src/components/Comment/CommentSection.vue')['default']
    CommentSectionItem: typeof import('./src/components/Comment/CommentSectionItem.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Filings: typeof import('./src/components/Filings/Filings.vue')['default']
    LableBar: typeof import('./src/components/LableBar/LableBar.vue')['default']
    MyCard: typeof import('./src/components/MyCard/MyCard.vue')['default']
    Nav: typeof import('./src/components/Nav/Nav.vue')['default']
    Notice: typeof import('./src/components/Notice/Notice.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timeline: typeof import('./src/components/Timeline/Timeline.vue')['default']
    TimelineItem: typeof import('./src/components/Timeline/TimelineItem.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar/TitleBar.vue')['default']
    TitleList: typeof import('./src/components/TitleList/TitleList.vue')['default']
    Waterfall: typeof import('./src/components/Waterfall/Waterfall.vue')['default']
    WebsiteInfo: typeof import('./src/components/WebsiteInfo/WebsiteInfo.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
